### ISSUE TITLE
"Learn" page doesn't have a footer

### ISSUE THREAD

**Issue by wiKapo** [BigBruhCoders/westerplatte-defenders#2]
All pages have a footer but there isn't one on the "learn" page.

I have tried to just add the line: `<Footer>{t("common:project")}</Footer>` but it obscures the main box. Here's how it looked
![image](https://user-images.githubusercontent.com/71190167/173225659-05aa310c-ae4a-409c-a24e-5f295c66b491.png)

**Comment by LempekPL** [comment]
footer was already fixed in main branch smh
